# Generated by Django 5.1.6 on 2025-02-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakureya', '0002_product_category_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ramen', 'Ramen'), ('sushi', 'Sushi'), ('bento', 'Bento'), ('tempura', 'Tempura'), ('mochi', 'Mochi')], default='Sin categoría', max_length=50),
        ),
    ]
