# Generated by Django 5.1.6 on 2025-02-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakureya', '0003_product_added_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
