# Generated by Django 5.1.6 on 2025-03-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakureya', '0004_alter_product_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sushi', 'Sushi'), ('ramen', 'Ramen'), ('yakitori', 'Yakitori '), ('donburi', 'Donburi'), ('postres', 'Postres')], default='Sin categoría', max_length=50),
        ),
    ]
