# Generated by Django 5.1.6 on 2025-04-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakureya', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sushi', 'Sushi'), ('ramen', 'Ramen'), ('yakitori', 'Yakitori'), ('donburi', 'Donburi'), ('postres', 'Postres'), ('bebidas', 'Bebidas')], default='Sin categoría', max_length=50),
        ),
    ]
