# Generated by Django 5.1.6 on 2025-04-30 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakureya', '0005_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('preparing', 'En preparación'), ('shipping', 'En camino'), ('delivered', 'Entregado'), ('canceled', 'Cancelado')], default='preparing', max_length=20)),
                ('address', models.TextField(verbose_name='Dirección de entrega')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_sale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio al momento de la venta')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakureya.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kakureya.sale')),
            ],
            options={
                'verbose_name': 'Ítem de venta',
                'verbose_name_plural': 'Ítems de venta',
            },
        ),
    ]
