# Generated by Django 5.1.6 on 2025-03-01 04:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakureya', '0005_product_is_active_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='added',
        ),
        migrations.AddField(
            model_name='product',
            name='added_by_users',
            field=models.ManyToManyField(blank=True, related_name='added_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ramen', 'Ramen'), ('sushi', 'Sushi'), ('bento', 'Bento'), ('tempura', 'Tempura'), ('mochi', 'Mochi')], default='Sin categoría', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
