# Generated by Django 5.1.6 on 2025-03-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakureya', '0006_remove_product_added_product_added_by_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
