# Generated by Django 5.1.6 on 2025-05-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakureya', '0006_userprofile_address_sale_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Pagado'),
        ),
        migrations.AddField(
            model_name='sale',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de transacción'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Referencia de pago'),
        ),
    ]
