# Generated by Django 5.1.6 on 2025-03-31 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakureya', '0005_alter_product_price'),
        ('kakureya', '0006_payment_created_at_alter_payment_transaction_id'),
    ]

    operations = [
    ]
