# Generated by Django 5.1.6 on 2025-03-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakureya', '0007_product_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='added_by_users',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sushi', 'Sushi'), ('ramen', 'Ramen'), ('yakitori', 'Yakitori '), ('donburi', 'Donburi'), ('postres', 'Postres')], default='Sin categoría', max_length=50),
        ),
    ]
