# Generated by Django 5.1.6 on 2025-06-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakureya', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='Nombre', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='APellido', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='second_last_name',
            field=models.CharField(default='Apellido', max_length=30),
            preserve_default=False,
        ),
    ]
